### ISSUE TITLE
Update http version

### ISSUE THREAD

**Issue by CoderNamedHendrick** [pratikbaid3/flutter_client_sse#14]
The package is running an earlier version of the HTTP package.
Because flutter_client_sse >=2.0.0-beta.1 depends on http ^0.13.5 and google_fonts 5.1.0 depends on http ^1.0.0, flutter_client_sse >=2.0.0-beta.1 is incompatible with google_fonts 5.1.0.
And because no versions of google_fonts match >5.1.0 <6.0.0, flutter_client_sse >=2.0.0-beta.1 is incompatible with google_fonts ^5.1.0.
So, because aku_staff_agent depends on both google_fonts ^5.1.0 and flutter_client_sse ^2.0.0, version solving failed.

**Comment by pratikbaid3** [comment]
Closing since this is now fixed in 2.0.1
