### ISSUE TITLE
Subscription hangs when server responds with 4xx status code

### ISSUE THREAD

**Issue by eye-dee** [pratikbaid3/flutter_client_sse#21]
Hello

Please take a look at the example project here: https://github.com/eye-dee/flutter_client_sse_validation
The client hangs on `--SUBSCRIBING TO SSE---`, when similar test with `OK` status code completes successfully

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5b94dbb4-9e59-4669-bd10-e36b4ee07eae">

**Comment by sharmaruchi30** [comment]
Hi @eye-dee, @pratikbaid3,

I encountered the same issue recently and discovered that it's due to the absence of a default case in the switch statement.

I'd like to work on this issue and will submit a PR soon if that's okay.

Thank you!

**Comment by pratikbaid3** [comment]
Hey @sharmaruchi30. All contributions are welcome. In the mean time, I'll also look into it.

**Comment by pratikbaid3** [comment]
Merged @sharmaruchi30 PR which logs a message on error resulting in the client looking like its hung. Hopefully, this provides a better development experience.

@eye-dee you would confirm if this fixes your issue. I'll close this once you confirm.

**Comment by eye-dee** [comment]
Hello @pratikbaid3 @sharmaruchi30 

Thank you for the quick fix, it works on my side as well
