### ISSUE TITLE
PlatformException(no_carrier_name, No carrier name, java.lang.SecurityException: Not allowed to access cell location, null)

### ISSUE THREAD

**Issue by Kay-coding** [pratikbaid3/flutter_client_sse#28]
android 14
flutter 3.23.0
I inquired about this related issue and added the ACCESS_FINE_LOCATION permission, but it still doesn't work. Has anyone encountered the same problem? If you know, please tell me. Thank you very much.

**Comment by pratikbaid3** [comment]
Hi @Kay-coding. Please elabourate on the issue. 

From the description, the issue is related using location permission. This package only facilitates network request and has nothing to do with location.

**Comment by pratikbaid3** [comment]
Marked as stale since there is no comment from author.
