### ISSUE TITLE
http post not working

### ISSUE THREAD

**Issue by glennmichaelmejias** [pratikbaid3/flutter_client_sse#8]
why http post cant work? i cant receive request even i do print log on the server

**Comment by pratikbaid3** [comment]
Hi. The current implementation of the service only caters to subscription of events through get. 

Ill add the post instance as a enhancement.

Thanks

**Comment by pratikbaid3** [comment]
Are you planning on sending a body with the subscription? 
@glennmichaelmejias

**Comment by glennmichaelmejias** [comment]
why there is regexp from your code? i am using this with openai chatgpt.

**Comment by pratikbaid3** [comment]
Hi @glennmichaelmejias. Http POST can now be used in the latest pre-release build of the package.
https://pub.dev/packages/flutter_client_sse/versions/2.0.0-beta.1

Thanks and Regards
